# CLI CALL - ws cloudformation create-stack --stack-name <StackName> --template-body file://<FileName> --capabilities CAPABILITY_IAM
# In some cases, must explicitly acknowledge that your stack template contains certain capabilities 
# If you have IAM resources, you can specify either capability (link to AWS CLI reference: https://docs.aws.amazon.com/cli/latest/reference/cloudformation/create-stack.html)
# Resources in this template affect permissions in AWS account
AWSTemplateFormatVersion: '2010-09-09'
Description: A CF template that creates IAM role for external service.
Resources:
  IAMRoleForExternalTool:
    Type: AWS::IAM::Role
    Properties: 
      Description: A test role for client.
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action: 'sts:AssumeRole'
        Tags:
          - Key: "Owner"
            Value: "Tyler-TU"
      # Path: /
      # Policies:
      #   - PolicyName: root
      #     PolicyDocument:
      #       Version: 2012-10-17
      #       Statement:
      #         - Effect: Allow
      #           Action: '*'
      #           Resource: '*'
  ExternalToolPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: TylerAssumeRolePolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Action:
          - iam:Get*
          - iam:List*
          - iam:Generate*
          Resource: "*"
