AWSTemplateFormatVersion: '2010-09-09'
Description: A simple CloudFormation template
Resources:
  S3Bucket: 
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'tyler-cf'
Outputs:
  BucketName:
    Value: !Ref 'S3Bucket'
    Description: Name of the S3 bucket for nested stacks.