AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SNSEmail:
    Type: String
    Description: Enter email for SNS notification.
Resources:
  SnsEmailTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        Endpoint: !Ref SNSEmail
        Protocol: Email